export const GLOBAL_STYLES = {
	COLOR: {
		PRIMARY: '#313FDD',
		SECONDARY: '#E6EBFF',
		ACCENT: '#F7F9FF',
		PRIMARY_DARK: '#000FB8',
		RED: '#E65252',
		GREEN: '#0BBB71',
		BORDER_COLOR: '#C1C4D2',
		DARK_TEXT: '#5B5B5B',
		LIGHT_TEXT: '#9A9A9A',
		SHADOW: '#DBCFE7',
		HORIZONTAL_LINE: '#efefef',
	},
}
